services:
  db-product:
    image: mysql:8.0
    container_name: db-product
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uproduct_user -psecure_password_product --silent" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_USER: product_user
      MYSQL_PASSWORD: secure_password_product
      MYSQL_ROOT_PASSWORD: secure_root_password_product
    ports:
      - "3306:3306"
    volumes:
      - db_data_product:/var/lib/mysql
    networks:
      - product-net

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db-product:
        condition: service_healthy
    networks:
      - product-net

networks:
  product-net:
    driver: bridge

volumes:
  db_data_product: